# Rustfmt configuration file

indent_style = "Block"

reorder_imports = true

blank_lines_upper_bound = 1;
blank_lines_lower_bound = 0;

bracket_style = "PreferSameLine";

fn_args_layout = "Tall";
fn_single_line = false;

force_multiline_blocks = true;

format_code_in_doc_comments = true;

indent_style = "Block";
inline_attribute_width = 0;

match_arm_blocks = true;
match_arm_leading_pipes = false;
match_arm_indent = true;
match_arm_trailing_comma = true;

normalize_comments = true;
remove_nested_parens = true;

space_after_colon = true;
space_before_colon = false;
space_around_ranges = true;

tab_spaces = 4;
trailing_comma = "Never";
trailing_semicolon = true;

where_single_line = false;

wrap_comments = true;
